// The Lucide icon catalog — the committed metadata artifact, loaded once at
// startup and searched lexically. No database, no embeddings: 1,594 short
// records with curated tags rank better by direct scoring than a vector arm
// could justify, and keeping icons OUT of the index means no schema bump, no
// re-embed, and no pollution of the component eval.
//
// The artifact (src/lucide-icons.json, cp'd into dist/ by the build script) is
// generated by scripts/vendor-icons.mjs from the lucide repo at the exact tag
// the registry pins for lucide-react — never hand-edited.
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { compareStrings, editDistance } from './text.ts'

export interface IconAlias {
  readonly name: string
  readonly deprecated: boolean
}

export interface IconEntry {
  /** Canonical kebab name, e.g. "house". */
  readonly name: string
  /** Primary component export, e.g. "House" (an <Name>Icon spelling also exists). */
  readonly pascal: string
  readonly tags: readonly string[]
  readonly categories: readonly string[]
  readonly aliases: readonly IconAlias[]
}

interface NameKey {
  readonly entry: IconEntry
  /** The alias this key came through, null for a canonical spelling. */
  readonly alias: IconAlias | null
}

export interface IconCatalog {
  /** The lucide tag the artifact was vendored from, e.g. "0.511.0". */
  readonly version: string
  readonly icons: readonly IconEntry[]
  /** Every accepted lowercase spelling (kebab, dashless/Pascal, aliases) → entry. */
  readonly byName: ReadonlyMap<string, NameKey>
  readonly categories: ReadonlySet<string>
}

const HERE = path.dirname(fileURLToPath(import.meta.url))

/** Resolved next to this file — identical from src/ (strip-types) and dist/. */
export function loadIconCatalog(
  file: string = path.resolve(HERE, 'lucide-icons.json'),
): IconCatalog {
  const raw = JSON.parse(readFileSync(file, 'utf8')) as {
    version: string
    icons: IconEntry[]
  }
  const byName = new Map<string, NameKey>()
  const categories = new Set<string>()
  for (const entry of raw.icons) {
    // Canonical spellings first so an alias can never shadow a real icon's name.
    byName.set(entry.name, { entry, alias: null })
    byName.set(entry.name.replace(/-/g, ''), { entry, alias: null }) // = pascal lowercased
    for (const category of entry.categories) categories.add(category)
  }
  for (const entry of raw.icons) {
    for (const alias of entry.aliases) {
      for (const key of [alias.name.toLowerCase(), alias.name.toLowerCase().replace(/-/g, '')]) {
        if (!byName.has(key)) byName.set(key, { entry, alias })
      }
    }
  }
  return { version: raw.version, icons: raw.icons, byName, categories }
}

export interface ResolvedIcon {
  readonly entry: IconEntry
  /** The alias the caller came through, null for a canonical spelling. */
  readonly alias: IconAlias | null
}

/**
 * Accepts every spelling an agent plausibly emits: kebab ("house"), PascalCase
 * ("House"), the Icon suffix ("HouseIcon"), the Lucide prefix ("LucideHouse"),
 * and legacy aliases in any of those forms ("Home", "alarm-check").
 */
export function resolveIconName(catalog: IconCatalog, input: string): ResolvedIcon | null {
  const lower = input
    .trim()
    .toLowerCase()
    .replace(/[\s_]+/g, '-')
  const bases = new Set([lower, lower.replace(/-/g, '')])
  const dashless = lower.replace(/-/g, '')
  if (dashless.startsWith('lucide') && dashless.length > 'lucide'.length) {
    bases.add(dashless.slice('lucide'.length))
  }
  if (dashless.endsWith('icon') && dashless.length > 'icon'.length) {
    bases.add(dashless.slice(0, -'icon'.length))
  }
  for (const base of bases) {
    const hit = catalog.byName.get(base)
    if (hit) return { entry: hit.entry, alias: hit.alias }
  }
  return null
}

/**
 * Lexical ranking over names, aliases, tags, and categories. Multi-term queries
 * are AND (every term must land somewhere); an icon's score is the sum of each
 * term's best signal, with a whole-query exact-name bonus on top. Shorter names
 * win ties — "arrow-up" beats "arrow-up-from-line" for "arrow up".
 */
export function matchIcons(
  catalog: IconCatalog,
  query: string,
  category?: string,
  limit = 8,
): IconEntry[] {
  const terms = query
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((t) => t.length > 1)
  const pool = category
    ? catalog.icons.filter((i) => i.categories.includes(category))
    : catalog.icons
  if (terms.length === 0) return pool.slice(0, limit)

  const wholeQuery = terms.join('-')
  const scored: { entry: IconEntry; score: number }[] = []
  for (const entry of pool) {
    let total = 0
    let dropped = false
    for (const term of terms) {
      let best = 0
      if (entry.name === term) best = 1000
      else if (entry.name.startsWith(term)) best = 600 - entry.name.length
      else if (entry.name.includes(term)) best = 400 - entry.name.length
      if (best < 900 && entry.aliases.some((a) => a.name === term)) best = Math.max(best, 900)
      if (best < 300) {
        for (const tag of entry.tags) {
          if (tag === term) best = Math.max(best, 300)
          else if (tag.startsWith(term)) best = Math.max(best, 200)
          else if (tag.includes(term)) best = Math.max(best, 120)
          if (best >= 300) break
        }
      }
      if (best < 80 && entry.categories.some((c) => c.includes(term))) best = 80
      if (best === 0) {
        dropped = true
        break
      }
      total += best
    }
    if (dropped) continue
    if (entry.name === wholeQuery) total += 1000
    else if (entry.aliases.some((a) => a.name === wholeQuery)) total += 900
    scored.push({ entry, score: total })
  }
  return scored
    .sort(
      (a, b) =>
        b.score - a.score ||
        a.entry.name.length - b.entry.name.length ||
        compareStrings(a.entry.name, b.entry.name),
    )
    .slice(0, limit)
    .map((s) => s.entry)
}

/** "Did you mean" over canonical names AND aliases — always returns canonical names. */
export function suggestIcons(catalog: IconCatalog, near: string, limit = 3): string[] {
  const target = near
    .trim()
    .toLowerCase()
    .replace(/[\s_]+/g, '-')
  const budget = Math.max(3, Math.ceil(target.length / 2))
  const seen = new Set<string>()
  return [...catalog.byName.entries()]
    .map(([key, { entry }]) => {
      const contains = key.includes(target) || target.includes(key)
      return { name: entry.name, contains, distance: editDistance(target, key) }
    })
    .filter((c) => c.contains || c.distance <= budget)
    .sort((a, b) => Number(b.contains) - Number(a.contains) || a.distance - b.distance)
    .filter((c) => !seen.has(c.name) && seen.add(c.name))
    .slice(0, limit)
    .map((c) => c.name)
}
