// GENERATED by scripts/build-rag-theme-assets.mjs in the encode-ui-registry
// repo, copied verbatim from src/lib/theme-engine-core.ts — DO NOT EDIT BY HAND.
// A clone of this repo cannot regenerate it; treat it as an input.
// The file is dependency-free BY CONTRACT (no imports, no node builtins, pure
// data + math), which is what lets the site, the build scripts and this MCP
// server run byte-identical validation.
// Theme engine v2 — the ONE home for the pure schema, defaults, merge, shadow
// composition, WCAG-AA clamp math, uniqueness distance math, and validation.
//
// Consumers: scripts/theme-resolve.mjs  (Node shell: adds the fs loaders and
//                                        re-exports everything here)
//            scripts/build-themes.mjs   (via the shell — site CSS + palettes-meta)
//            scripts/build-manifest.mjs (via the shell — registry:theme payloads)
//            the Theme Studio drawer    (browser: build-accurate validation/preview)
//            worker/dev/vite-theme-studio-plugin.ts (dev write-path validation)
//
// This module is browser-safe BY CONTRACT: no node builtins, no fs, no console
// side effects — pure data + math only. Node scripts import it with an explicit
// `.ts` extension under type stripping (build-icons.mjs precedent), so the
// syntax must stay ERASABLE (interfaces/type aliases fine; no enums, no
// namespaces, no parameter properties).
//
// Schema (v2 — flat keys, interoperable with common shadcn theme-editor exports;
// every v2 key OPTIONAL so the 40 vendored entries stay valid byte-unchanged):
//   light: 32 colour tokens + radius (required)  + optional shared keys
//   dark:  32 colour tokens (required)           + optional per-mode overrides
// Shared keys live in `light` and apply to both modes (like `radius` always
// has); `dark` may override only the shadow six-pack — fonts/tracking/motion/
// radius/spacing are mode-invariant by construction.

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** An OKLCH colour as numbers (L 0..1, C unbounded ~0..0.4, H degrees). */
export interface Oklch {
  L: number
  C: number
  H: number
}

/** parseOklch() result: numbers plus the raw C/H substrings for round-tripping. */
export interface ParsedOklch extends Oklch {
  rawC: string
  rawH: string
}

/** One mode block (or resolved surface): flat token → value strings. */
export type ModeVars = Record<string, string>

/** A schema-valid preset entry (post-validation shape). */
export interface PresetDef {
  character?: string
  light: ModeVars
  dark: ModeVars
}

/** An UNVALIDATED preset entry, as parsed from JSON or user input. */
export interface RawPresetEntry {
  character?: unknown
  light?: ModeVars
  dark?: ModeVars
}

export interface ClampReport {
  log: string[]
  skips: string[]
  residuals: string[]
}

export interface FontFile {
  path: string
  weight: string
  style: string
}

export interface FontEntry {
  family: string
  category: string
  files: FontFile[]
  license?: string
  source?: string
}

/** src/themes/fonts.json minus its $comment: slug → family entry. */
export type FontsManifest = Record<string, FontEntry>

export interface FontStack {
  stack: string
  files: string[]
  passthrough?: boolean
  entry?: FontEntry
}

/** A point in OKLab cartesian space (for ΔE). */
export interface OklabPoint {
  L: number
  a: number
  b: number
}

// ---------------------------------------------------------------------------
// Token vocabulary
// ---------------------------------------------------------------------------

/** The 32 semantic colour tokens every palette defines in both modes. */
export const COLOR_TOKENS = [
  'background',
  'foreground',
  'card',
  'card-foreground',
  'popover',
  'popover-foreground',
  'primary',
  'primary-foreground',
  'secondary',
  'secondary-foreground',
  'muted',
  'muted-foreground',
  'accent',
  'accent-foreground',
  'destructive',
  'destructive-foreground',
  'border',
  'input',
  'ring',
  'chart-1',
  'chart-2',
  'chart-3',
  'chart-4',
  'chart-5',
  'sidebar',
  'sidebar-foreground',
  'sidebar-primary',
  'sidebar-primary-foreground',
  'sidebar-accent',
  'sidebar-accent-foreground',
  'sidebar-border',
  'sidebar-ring',
] as const

export type ColorToken = (typeof COLOR_TOKENS)[number]

/** The composed shadow ramp keys, in emission order (bare `shadow` included). */
export const SHADOW_STEP_KEYS = [
  'shadow-2xs',
  'shadow-xs',
  'shadow-sm',
  'shadow',
  'shadow-md',
  'shadow-lg',
  'shadow-xl',
  'shadow-2xl',
] as const

export type ShadowStepKey = (typeof SHADOW_STEP_KEYS)[number]

/** The six authored shadow knobs; composed into the 8-step ramp. */
export const SHADOW_KNOBS = [
  'shadow-color',
  'shadow-opacity',
  'shadow-blur',
  'shadow-spread',
  'shadow-offset-x',
  'shadow-offset-y',
] as const

export type ShadowKnob = (typeof SHADOW_KNOBS)[number]

/** Mode-invariant v2 keys (authored in `light`, apply to both modes). */
export const V2_SHARED_KEYS = [
  'font-sans',
  'font-serif',
  'font-mono',
  'letter-spacing',
  'ease-in',
  'ease-out',
  'ease-in-out',
  'default-transition-duration',
  'default-transition-timing-function',
  'spacing',
] as const

export type V2SharedKey = (typeof V2_SHARED_KEYS)[number]

/** Every key legal in a `light` block (32 colours + radius + overlay + knobs + shared). */
export const LIGHT_KEYS: ReadonlySet<string> = new Set<string>([
  ...COLOR_TOKENS,
  'radius',
  'overlay',
  ...SHADOW_KNOBS,
  ...V2_SHARED_KEYS,
])
// dark may re-anchor the shadow ramp and the modal scrim, but nothing else.
export const DARK_KEYS: ReadonlySet<string> = new Set<string>([
  ...COLOR_TOKENS,
  'overlay',
  ...SHADOW_KNOBS,
])

// ---------------------------------------------------------------------------
// Defaults (Tailwind v4.3.3 values — theme.app.css must render today's page
// byte-visually identical when a preset authors none of the v2 keys)
// ---------------------------------------------------------------------------

export const TW_DEFAULTS: Record<string, string> = {
  'font-sans':
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', 'Noto Sans', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  'font-serif': "ui-serif, Georgia, Cambria, 'Times New Roman', Times, serif",
  'font-mono':
    "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  'tracking-normal': '0em',
  'ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
  'ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
  'ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
  'default-transition-duration': '150ms',
  'default-transition-timing-function': 'cubic-bezier(0.4, 0, 0.2, 1)',
  spacing: '0.25rem',
}

/**
 * Tailwind's literal shadow ramp. Used VERBATIM when a preset authors no shadow
 * knob, so un-branded palettes keep exactly today's shadows (the composed ramp
 * intentionally differs from Tailwind at md+ — see composeShadows()).
 */
export const DEFAULT_SHADOWS: Record<string, string> = {
  'shadow-2xs': '0 1px rgb(0 0 0 / 0.05)',
  'shadow-xs': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
  'shadow-sm': '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
  shadow: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
  'shadow-md': '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
  'shadow-lg': '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
  'shadow-xl': '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
  'shadow-2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
}

/** Neutral knob set filling UNAUTHORED knobs once a preset authors at least one. */
export const DEFAULT_SHADOW_KNOBS: Record<ShadowKnob, string> = {
  'shadow-color': 'oklch(0 0 0)',
  'shadow-opacity': '0.1',
  'shadow-blur': '3px',
  'shadow-spread': '0px',
  'shadow-offset-x': '0px',
  'shadow-offset-y': '1px',
}

// ---------------------------------------------------------------------------
// Shadow composition — 6 knobs → the 8-step ramp:
// 2xs/xs single-layer at opacity×0.5; sm/shadow/md/lg/xl two-layer with fixed
// second-layer offset-y/blur pairs and spread₂ = spread − 1px; 2xl at ×2.5.
// A brand authors six numbers and the whole elevation ramp stays coherent.
// ---------------------------------------------------------------------------

/** Inject an alpha into an oklch()/hsl() colour that carries none. */
export const withAlpha = (color: string, alpha: number): string => {
  const a = Math.round(alpha * 1000) / 1000
  const m = /^(oklch|hsl)\(\s*([^/)]+?)\s*\)$/.exec(color.trim())
  if (!m) return color
  return `${m[1]}(${m[2]} / ${a})`
}

// Literal keys, not an index signature: the second-layer pair is read by name
// below, and a widened Record would make each lookup `| undefined`.
const TWO_LAYER = {
  'shadow-sm': ['1px', '2px'],
  shadow: ['1px', '2px'],
  'shadow-md': ['2px', '4px'],
  'shadow-lg': ['4px', '6px'],
  'shadow-xl': ['8px', '10px'],
} as const satisfies Record<string, readonly [string, string]>

export function composeShadows(knobs: ModeVars): Record<string, string> {
  // `?? default` is exactly the old `{ ...DEFAULT_SHADOW_KNOBS, ...knobs }`
  // spread for every defined value, and it keeps the read typed as string.
  const knob = (key: ShadowKnob): string => knobs[key] ?? DEFAULT_SHADOW_KNOBS[key]
  const color = knob('shadow-color')
  const opacity = parseFloat(knob('shadow-opacity'))
  const x = knob('shadow-offset-x')
  const y = knob('shadow-offset-y')
  const blur = knob('shadow-blur')
  const spread = knob('shadow-spread')
  const spread2 = `${parseFloat(spread) - 1}px`
  const layer = (alphaMul: number) =>
    `${x} ${y} ${blur} ${spread} ${withAlpha(color, opacity * alphaMul)}`
  const twoLayer = (step: keyof typeof TWO_LAYER) => {
    const [offsetY, secondBlur] = TWO_LAYER[step]
    return `${layer(1)}, ${x} ${offsetY} ${secondBlur} ${spread2} ${withAlpha(color, opacity)}`
  }
  // Key order is the ramp order — it is what the generated CSS emits.
  return {
    'shadow-2xs': layer(0.5),
    'shadow-xs': layer(0.5),
    'shadow-sm': twoLayer('shadow-sm'),
    shadow: twoLayer('shadow'),
    'shadow-md': twoLayer('shadow-md'),
    'shadow-lg': twoLayer('shadow-lg'),
    'shadow-xl': twoLayer('shadow-xl'),
    'shadow-2xl': layer(2.5),
  }
}

// ---------------------------------------------------------------------------
// Fonts — manifest lookups (pure half; the fs loader lives in theme-resolve.mjs)
// ---------------------------------------------------------------------------

const FALLBACKS: Record<string, string> = {
  sans: 'ui-sans-serif, system-ui, sans-serif',
  serif: "ui-serif, Georgia, 'Times New Roman', serif",
  mono: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
  handwriting: 'cursive',
}

/**
 * Manifest sanity, pure form: every declared file must satisfy `fileExists`
 * (the Node shells pass an fs probe; a browser caller can pass `() => true`),
 * categories must be known. Returns error strings, [] when clean.
 */
export function validateFontsManifestData(
  manifest: FontsManifest,
  fileExists: (path: string) => boolean,
): string[] {
  const errors: string[] = []
  for (const [slug, entry] of Object.entries(manifest)) {
    if (!entry.family) errors.push(`fonts.json ${slug}: missing "family"`)
    if (!FALLBACKS[entry.category])
      errors.push(`fonts.json ${slug}: unknown category "${entry.category}"`)
    for (const f of entry.files ?? []) {
      if (!fileExists(f.path)) {
        errors.push(`fonts.json ${slug}: file not on disk: public${f.path}`)
      }
    }
    if (!(entry.files ?? []).length) errors.push(`fonts.json ${slug}: no files`)
  }
  return errors
}

const manifestEntry = (manifest: FontsManifest, family: string): FontEntry | null =>
  Object.values(manifest).find((f) => f.family === family) ?? manifest[family] ?? null

/**
 * Resolve an authored font value: a single family name must exist in the
 * manifest (self-hosted) and gains its category fallback stack; a raw
 * comma-separated stack passes through verbatim (external theme-export imports).
 */
export function resolveFontStack(value: string, manifest: FontsManifest): FontStack | null {
  if (value.includes(',')) return { stack: value, files: [], passthrough: true }
  const entry = manifestEntry(manifest, value)
  if (!entry) return null
  const fallback = FALLBACKS[entry.category] ?? FALLBACKS.sans
  const quoted = entry.family.includes(' ') ? `'${entry.family}'` : entry.family
  return { stack: `${quoted}, ${fallback}`, files: entry.files.map((f) => f.path), entry }
}

// ---------------------------------------------------------------------------
// WCAG-AA contrast clamp — ported from ProjectClaude scripts/build-theme-presets.mjs
// (the house pattern). Text-bearing fg/surface pairs at 4.5:1, both modes; a
// failing pair is repaired by moving the FOREGROUND's OKLCH lightness (chroma +
// hue preserved); ratios computed on the 8-bit-quantized sRGB the browser
// actually paints (what axe measures). Residuals are the caller's build failure.
// ---------------------------------------------------------------------------

/** fg token → the surfaces its text renders on (4.5:1 against EACH). */
export const CONTRAST_PAIRS: readonly (readonly [string, readonly string[]])[] = [
  ['foreground', ['background']],
  ['card-foreground', ['card']],
  ['popover-foreground', ['popover']],
  ['primary-foreground', ['primary']],
  ['secondary-foreground', ['secondary']],
  // muted text renders on the page, on cards, and on muted surfaces alike.
  ['muted-foreground', ['muted', 'background', 'card']],
  ['accent-foreground', ['accent']],
  ['destructive-foreground', ['destructive']],
  ['sidebar-foreground', ['sidebar']],
  ['sidebar-primary-foreground', ['sidebar-primary']],
  ['sidebar-accent-foreground', ['sidebar-accent']],
]
export const AA_TARGET = 4.5

/** Parse `oklch(L C H)` (L/C may carry %, H may carry `deg`; no alpha). */
export const parseOklch = (str: string | undefined): ParsedOklch | null => {
  if (!str) return null
  const m = /^oklch\(\s*([\d.]+)(%?)\s+([\d.]+)(%?)\s+([\d.]+)(?:deg)?\s*\)$/.exec(str.trim())
  if (!m) return null
  // Every group is non-optional, so a match guarantees all five. The
  // destructuring defaults are unreachable — they exist to keep the reads typed.
  const [, rawL = '', pctL = '', rawC = '', pctC = '', rawH = ''] = m
  const L = parseFloat(rawL) / (pctL ? 100 : 1)
  const C = parseFloat(rawC) / (pctC ? 100 : 1)
  return { L, C, H: parseFloat(rawH), rawC: rawC + pctC, rawH }
}

/** OKLCH → linear sRGB (Björn Ottosson's OKLab matrices), unclipped. */
export const oklchToLinearSrgb = ({ L, C, H }: Oklch): [number, number, number] => {
  const hr = (H * Math.PI) / 180
  const a = C * Math.cos(hr)
  const b = C * Math.sin(hr)
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ]
}

const srgbEncode = (c: number): number =>
  c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055

/** WCAG relative luminance of the 8-bit-quantized sRGB rendering (axe's view). */
export const luminance = (oklch: Oklch): number => {
  const dec = (c: number) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)
  // Per channel rather than through .map(), which widens the tuple to number[].
  const chan = (c: number) => dec(Math.round(srgbEncode(Math.min(1, Math.max(0, c))) * 255) / 255)
  const [r, g, b] = oklchToLinearSrgb(oklch)
  return 0.2126 * chan(r) + 0.7152 * chan(g) + 0.0722 * chan(b)
}

export const ratio = (fg: Oklch, bg: Oklch): number => {
  const yf = luminance(fg)
  const yb = luminance(bg)
  return (Math.max(yf, yb) + 0.05) / (Math.min(yf, yb) + 0.05)
}

/** Binary-search fg.L in one direction (monotone side of the surface's L). */
const searchL = (fg: Oklch, bg: Oklch, lighten: boolean): number | null => {
  let lo = lighten ? Math.max(fg.L, bg.L) : 0
  let hi = lighten ? 1 : Math.min(fg.L, bg.L)
  if (ratio({ ...fg, L: lighten ? hi : lo }, bg) < AA_TARGET) return null
  for (let i = 0; i < 48; i++) {
    const mid = (lo + hi) / 2
    const passes = ratio({ ...fg, L: mid }, bg) >= AA_TARGET
    if (passes === lighten) hi = mid
    else lo = mid
  }
  let L = Math.round((lighten ? hi : lo) * 10000) / 10000
  // 4-decimal rounding may fall a hair short — nudge until the rounded value passes.
  for (let i = 0; i < 20 && ratio({ ...fg, L }, bg) < AA_TARGET; i++) {
    L = Math.round((L + (lighten ? 0.0001 : -0.0001)) * 10000) / 10000
  }
  return ratio({ ...fg, L }, bg) >= AA_TARGET ? L : null
}

/**
 * Repair a failing pair by moving fg.L. Prefer moving AWAY from the surface
 * (smallest perceptual change); when that side is exhausted (e.g. white text on
 * a mid-tone primary — L=1 still under AA), FLIP the text to the other polarity
 * (dark text on the same surface). One of the two always exists: no surface
 * luminance fails both black and white at 4.5:1.
 */
export const clampL = (fg: Oklch, bg: Oklch): number | null => {
  const away = luminance(fg) >= luminance(bg)
  return searchL(fg, bg, away) ?? searchL(fg, bg, !away)
}

/** Audit + repair one mode map in place, appending to report {log,skips,residuals}. */
export const clampModeVars = (
  preset: string,
  mode: string,
  vars: ModeVars,
  report: ClampReport,
): void => {
  for (const [fgTok, surfaces] of CONTRAST_PAIRS) {
    for (let pass = 0; pass < 5; pass++) {
      const fg = parseOklch(vars[fgTok])
      if (!fg) {
        if (pass === 0) report.skips.push(`${preset}.${mode}.${fgTok}: unparsable "${vars[fgTok]}"`)
        break
      }
      const parsed = surfaces
        .map((s) => ({ s, bg: parseOklch(vars[s]) }))
        .filter((entry): entry is { s: string; bg: ParsedOklch } => {
          if (!entry.bg && pass === 0) {
            report.skips.push(`${preset}.${mode}.${entry.s}: unparsable "${vars[entry.s]}"`)
          }
          return entry.bg !== null
        })
      const failing = parsed
        .map((p) => ({ ...p, r: ratio(fg, p.bg) }))
        .filter((p) => p.r < AA_TARGET)
        .sort((a, b) => a.r - b.r)
      const worst = failing[0]
      if (!worst) break
      const newL = clampL(fg, worst.bg)
      if (newL === null || pass === 4) {
        report.residuals.push(
          `${preset}.${mode}: ${fgTok} vs ${worst.s} = ${worst.r.toFixed(2)} (unrepairable)`,
        )
        break
      }
      const oldValue = vars[fgTok]
      vars[fgTok] = `oklch(${newL} ${fg.rawC} ${fg.rawH})`
      report.log.push(
        `${preset}.${mode}.${fgTok}: vs ${worst.s} ${worst.r.toFixed(2)} → ` +
          `${ratio({ ...fg, L: newL }, worst.bg).toFixed(2)}  (${oldValue} → ${vars[fgTok]})`,
      )
    }
  }
}

/** Post-clamp re-audit: append any parsable pair still under AA to residuals. */
export const auditResiduals = (
  preset: string,
  mode: string,
  vars: ModeVars,
  report: ClampReport,
): void => {
  for (const [fgTok, surfaces] of CONTRAST_PAIRS) {
    const fg = parseOklch(vars[fgTok])
    if (!fg) continue
    for (const s of surfaces) {
      const bg = parseOklch(vars[s])
      if (bg && ratio(fg, bg) < AA_TARGET) {
        report.residuals.push(`${preset}.${mode}: ${fgTok} vs ${s} = ${ratio(fg, bg).toFixed(2)}`)
      }
    }
  }
}

/** OKLCH → `#rrggbb` of the 8-bit sRGB rendering (for <meta name="theme-color">). */
export const oklchToHex = (oklch: Oklch): string => {
  const hex = oklchToLinearSrgb(oklch)
    .map((c) => Math.min(1, Math.max(0, c)))
    .map((c) => Math.round(srgbEncode(c) * 255))
    .map((v) => v.toString(16).padStart(2, '0'))
    .join('')
  return `#${hex}`
}

const srgbDecode = (c: number): number => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)

/**
 * `#rgb`/`#rrggbb` → OKLCH (inverse gamma → Ottosson's inverse sRGB→OKLab
 * matrices → LCH), rounded to 4 decimals — the house serialization precision.
 * Every hex is in-gamut by construction, so no gamut mapping is needed on this
 * direction; near-achromatic results collapse to C=0 H=0 (hue is noise there).
 * Returns null for anything that is not a 3/6-digit hex literal.
 */
export const hexToOklch = (hex: string): Oklch | null => {
  const m = /^#(?:([0-9a-f]{3})|([0-9a-f]{6}))$/i.exec(hex.trim())
  if (!m) return null
  // Exactly one of the two groups matches, so each fallback below is unreachable.
  const [, three = '', sixRaw] = m
  const six = sixRaw ?? [...three].map((ch) => ch + ch).join('')
  // Per channel rather than through .map(), which widens the tuple to number[].
  const chan = (i: number) => srgbDecode(parseInt(six.slice(i, i + 2), 16) / 255)
  const r = chan(0)
  const g = chan(2)
  const b = chan(4)
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b)
  const mm = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b)
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b)
  const L = 0.2104542553 * l + 0.793617785 * mm - 0.0040720468 * s
  const a = 1.9779984951 * l - 2.428592205 * mm + 0.4505937099 * s
  const bb = 0.0259040371 * l + 0.7827717662 * mm - 0.808675766 * s
  const round4 = (n: number) => Math.round(n * 10000) / 10000
  const C = Math.hypot(a, bb)
  if (C < 0.0001) return { L: round4(L), C: 0, H: 0 }
  const H = ((Math.atan2(bb, a) * 180) / Math.PI + 360) % 360
  return { L: round4(L), C: round4(C), H: round4(H) }
}

/** Numbers → the house `oklch(L C H)` string form (bare numbers, no %, no deg). */
export const formatOklch = ({ L, C, H }: Oklch): string => `oklch(${L} ${C} ${H})`

// ---------------------------------------------------------------------------
// Uniqueness distance math — palette ANCHOR comparisons (light-mode primary).
// Consumed by build-themes.mjs (uniqueness.json) and the Theme Studio's
// anchor plate / floor evaluator, so both read the same geometry.
// ---------------------------------------------------------------------------

export const toLab = ({ L, C, H }: Oklch): OklabPoint => {
  const hr = (H * Math.PI) / 180
  return { L, a: C * Math.cos(hr), b: C * Math.sin(hr) }
}

/** OKLab Euclidean ΔE between two anchors, rounded to 4 decimals. */
export const dEok = (p: Oklch, q: Oklch): number => {
  const [A, B] = [toLab(p), toLab(q)]
  return Math.round(Math.hypot(A.L - B.L, A.a - B.a, A.b - B.b) * 10000) / 10000
}

/** Hue distance in degrees (1 decimal) — null when either anchor is near-achromatic. */
export const dHue = (p: Oklch, q: Oklch): number | null => {
  if (p.C < 0.03 || q.C < 0.03) return null
  const d = Math.abs(p.H - q.H) % 360
  return Math.round((d > 180 ? 360 - d : d) * 10) / 10
}

// ---------------------------------------------------------------------------
// Resolution — Partial-over-defaults. Emission stays the caller's business.
// ---------------------------------------------------------------------------

const authoredShadow = (vars: ModeVars): boolean => SHADOW_KNOBS.some((k) => k in vars)

/**
 * Fully resolve one preset: merge over defaults, compose shadows, resolve font
 * stacks, rename letter-spacing → tracking-normal. Returns flat token → value
 * maps whose keys are the EMITTED custom-property names (minus `--`).
 */
export function resolvePreset(
  preset: PresetDef,
  manifest: FontsManifest = {},
): { light: ModeVars; dark: ModeVars } {
  const { light, dark } = preset
  const out: { light: ModeVars; dark: ModeVars } = { light: {}, dark: {} }

  // validatePresets() already required all 32 in both modes, so the guards below
  // never skip on a valid entry — they keep the write typed without a cast.
  for (const tok of COLOR_TOKENS) {
    const l = light[tok]
    const d = dark[tok]
    if (l !== undefined) out.light[tok] = l
    if (d !== undefined) out.dark[tok] = d
  }
  out.light.radius = light.radius ?? '0.625rem'
  // Modal scrim base colour (dialog/sheet/drawer overlays paint bg-overlay/80 etc.).
  // Default black = pixel-identical to the upstream bg-black scrims.
  out.light.overlay = light.overlay ?? 'oklch(0 0 0)'
  out.dark.overlay = dark.overlay ?? out.light.overlay

  // Every key read below is a literal present in TW_DEFAULTS; the '' fallback
  // exists only to keep the lookup typed.
  const twDefault = (key: string): string => TW_DEFAULTS[key] ?? ''
  for (const key of ['font-sans', 'font-serif', 'font-mono']) {
    const authored = light[key]
    if (!authored) {
      out.light[key] = twDefault(key)
      continue
    }
    const resolved = resolveFontStack(authored, manifest)
    out.light[key] = resolved ? resolved.stack : authored
  }
  out.light['tracking-normal'] = light['letter-spacing'] ?? twDefault('tracking-normal')
  for (const key of [
    'ease-in',
    'ease-out',
    'ease-in-out',
    'default-transition-duration',
    'default-transition-timing-function',
  ]) {
    out.light[key] = light[key] ?? twDefault(key)
  }
  if (light.spacing) out.light.spacing = light.spacing

  // Shadows: untouched presets keep Tailwind's literal ramp; any authored knob
  // switches the mode (and dark inherits light's knobs unless it re-anchors).
  const authoredKnobs = (vars: ModeVars): ModeVars => {
    const knobs: ModeVars = {}
    for (const k of SHADOW_KNOBS) {
      const v = vars[k]
      if (v) knobs[k] = v
    }
    return knobs
  }
  const lightKnobs = authoredKnobs(light)
  const darkKnobs = authoredKnobs(dark)
  const lightRamp = authoredShadow(light) ? composeShadows(lightKnobs) : { ...DEFAULT_SHADOWS }
  const darkRamp =
    authoredShadow(light) || authoredShadow(dark)
      ? composeShadows({ ...lightKnobs, ...darkKnobs })
      : { ...DEFAULT_SHADOWS }
  Object.assign(out.light, lightRamp)
  Object.assign(out.dark, darkRamp)

  return out
}

// ---------------------------------------------------------------------------
// Validation + clamping (pure — the fs loader wrapping these lives in
// scripts/theme-resolve.mjs)
// ---------------------------------------------------------------------------

const LENGTH_RE = /^-?[\d.]+(px|rem|em)$/
const isLength = (v: string): boolean => v === '0' || LENGTH_RE.test(v)

// Motion + scrim value shapes. These matter because resolvePreset defaults with
// `??`, which does NOT catch '' — an empty string would survive resolution and
// emit `--overlay: ;`, a declaration the browser drops, leaving every modal
// scrim transparent with no build error.
const EASING_KEYWORDS = new Set([
  'linear',
  'ease',
  'ease-in',
  'ease-out',
  'ease-in-out',
  'step-start',
  'step-end',
])
const isEasing = (v: string): boolean =>
  EASING_KEYWORDS.has(v) || /^(cubic-bezier|steps|linear)\(.+\)$/.test(v)
const isDuration = (v: string): boolean => /^[\d.]+m?s$/.test(v)
const isColorFn = (v: string): boolean => /^(oklch|hsl)\(/.test(v)

export function validatePresets(
  presets: Record<string, RawPresetEntry>,
  manifest: FontsManifest = {},
): { errors: string[]; warnings: string[] } {
  const errors: string[] = []
  const warnings: string[] = []
  for (const [name, p] of Object.entries(presets)) {
    for (const key of Object.keys(p)) {
      if (!['character', 'light', 'dark'].includes(key)) {
        errors.push(`${name}: unknown entry key "${key}"`)
      }
    }
    if (typeof p.character !== 'string' || !p.character.trim()) {
      errors.push(`${name}: missing/empty "character"`)
    }
    if (!p.light || !p.dark) {
      errors.push(`${name}: missing light/dark block`)
      continue
    }
    for (const tok of COLOR_TOKENS) {
      if (!p.light[tok]) errors.push(`${name}.light: missing colour "${tok}"`)
      if (!p.dark[tok]) errors.push(`${name}.dark: missing colour "${tok}"`)
    }
    if (!p.light.radius) errors.push(`${name}.light: missing "radius"`)
    for (const [mode, allowed, vars] of [
      ['light', LIGHT_KEYS, p.light],
      ['dark', DARK_KEYS, p.dark],
    ] as const) {
      for (const key of Object.keys(vars)) {
        if (!allowed.has(key)) errors.push(`${name}.${mode}: unknown token "${key}"`)
      }
    }
    for (const [mode, vars] of [
      ['light', p.light],
      ['dark', p.dark],
    ] as const) {
      for (const key of [
        'radius',
        'letter-spacing',
        'spacing',
        'shadow-blur',
        'shadow-spread',
        'shadow-offset-x',
        'shadow-offset-y',
      ]) {
        if (vars[key] !== undefined && !isLength(vars[key])) {
          errors.push(`${name}.${mode}: "${key}" is not a CSS length: "${vars[key]}"`)
        }
      }
      if (vars['shadow-opacity'] !== undefined) {
        const o = parseFloat(vars['shadow-opacity'])
        if (!(o >= 0 && o <= 1)) errors.push(`${name}.${mode}: shadow-opacity out of [0,1]`)
      }
      for (const key of ['shadow-color', 'overlay']) {
        if (vars[key] !== undefined && !isColorFn(vars[key])) {
          errors.push(`${name}.${mode}: ${key} must be oklch()/hsl(): "${vars[key]}"`)
        }
      }
    }
    for (const key of [
      'ease-in',
      'ease-out',
      'ease-in-out',
      'default-transition-timing-function',
    ]) {
      const v = p.light[key]
      if (v !== undefined && !isEasing(v)) {
        errors.push(`${name}.light: "${key}" is not a CSS easing function: "${v}"`)
      }
    }
    if (
      p.light['default-transition-duration'] !== undefined &&
      !isDuration(p.light['default-transition-duration'])
    ) {
      errors.push(
        `${name}.light: "default-transition-duration" is not a CSS time: "${p.light['default-transition-duration']}"`,
      )
    }
    if (p.light.spacing) {
      warnings.push(
        `${name}: sets "spacing" — rescales every p-*/gap-*/h-* incl. the demo stages; make sure that is deliberate`,
      )
    }
    for (const key of ['font-sans', 'font-serif', 'font-mono']) {
      const v = p.light[key]
      if (!v) continue
      if (v.includes(',')) {
        warnings.push(`${name}: raw font stack for ${key} (passthrough, no @font-face emitted)`)
      } else if (!resolveFontStack(v, manifest)) {
        errors.push(`${name}: ${key} family "${v}" is not in src/themes/fonts.json`)
      }
    }
  }
  return { errors, warnings }
}

/**
 * AA-clamp every palette (both modes) on a deep-ish copy — presets.json stays
 * pristine vendored data; the clamp is a build transformation, exactly like the
 * family scaffold's. Returns the clamped catalogue + the report.
 */
export function clampPresets(presets: Record<string, PresetDef>): {
  presets: Record<string, PresetDef>
  report: ClampReport
} {
  const report: ClampReport = { log: [], skips: [], residuals: [] }
  const out: Record<string, PresetDef> = {}
  for (const [name, p] of Object.entries(presets)) {
    const light = { ...p.light }
    const dark = { ...p.dark }
    clampModeVars(name, 'light', light, report)
    clampModeVars(name, 'dark', dark, report)
    out[name] = { ...p, light, dark }
  }
  // Post-clamp re-audit: any parsable pair still under AA is a build failure.
  for (const [name, p] of Object.entries(out)) {
    auditResiduals(name, 'light', p.light, report)
    auditResiduals(name, 'dark', p.dark, report)
  }
  return { presets: out, report }
}
